language: go
go:
- '1.8'
- '1.9'
- '1.10'
- master
matrix:
  allow_failures:
  - go: master
script: go test -v -race -cpu=1,2,4 -bench . -benchmem ./...
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_GO_VERSION = '1.10'"
env:
  global:
    # travis encrypt --add GITHUB_TOKEN=$GITHUB_TOKEN
    secure: JIsGOJapsU/oSyZX6fyCC+s8Jjlmmr7SAlP55KhUi1pZbQ18Saszs/zRo5Og+wPtwj5teikcSSYec9ZyuLnDX/j6N0LMkSMSldSCgR2lv9uQI1zmtUMjYTI44f9LgtHN6JvTjiH6zxW5HSZJta+4p6LjpxOYaUhA4A5FPGSHs6MF/kXtgA0ufc640GMzTrFcBrnVN4DXR1UlAqMnt9lQ2FgI+rJ1PfVDoho6m2Uz7XGsarYQSTm/l2sfEkNtCJjKDLEc0tEYCuCUUPnbhaJgQIlTpCo03dR30CoSArkkagNWfSYcKwoV+bBryHK08GNHvXtm3LarRPDe8MdN0a4TwC26boUjYtQfrabI0Q7d1EhpXGSL0dNVwiakK76xwOi8b3UfBog5I3fB2u7R0HsiLhxQzf1GMTS6Vx41xAByomGMcXfg6pCxZ5Q/l2Xs/IepC6xMWHyTvFV8EDnRaECHJNPZPXdhvGSOzGOsRWM+eVcC8k67YovTS9bzcaVEMFDZ+5SO91YX2dKstUhEt6T/b6pRktc0+herk4iUicMT9E9G1I/l9Zyz6reFW3XioPqt53uYq5O3jB4rDmbgiPdPKdayrufXZtV15GLTEG5AhVfG5/u/zafrHkzLftWLu23gLVfWLQ5CmpbFp2wZl4tYH+7uMKGFFWuX8ZkllojqozI=
